# See: https://prettier.io/docs/en/configuration.html
trailingComma: 'all'
singleQuote: true
semi: true
overrides:
  - files: ['*.html']
    options:
      parser: 'angular'
      singleAttributePerLine: true
