version: '3.7'

services:
  db:
    image: 'postgres:9.6'
    init: true
    environment:
      - POSTGRES_USER=cpdw
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
    ports:
      - '${POSGRES_PORT}:5432'
